### ISSUE TITLE
Allow changing the order of a chain

### ISSUE THREAD

**Issue by lemoncove** [otac0n/markov#1]
If I want to walk a chain a new chain with hundreds of thousands of inputs, it will take awhile to add all of those inputs.

If I want to walk the same chain, except with a different order, I'd need to create an entirely new chain object, eating a lot of memory and taking an equally long amount of time to add the same inputs.

**Comment by otac0n** [comment]
Much more of the state has been exposed in v2.0.

This should enable such scenarios, as well as persisting and loading the state in a more efficient format.

See the tests for a quick example:
https://github.com/otac0n/markov/blob/master/Markov.Tests/MarkovChainTests.cs

**Comment by lemoncove** [comment]
Hey, neat! Thanks for the update.
